// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PensionerDetailMicroservice.Data;

namespace PensionerDetailMicroservice.Migrations
{
    [DbContext(typeof(MTwoPensionDbContext))]
    partial class MTwoPensionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PensionerDetailMicroservice.Models.PensionerDetailModel", b =>
                {
                    b.Property<long>("aadharno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("accno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("allowances")
                        .HasColumnType("bigint");

                    b.Property<string>("bankname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("banktype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pensiontype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("salaryearned")
                        .HasColumnType("bigint");

                    b.HasKey("aadharno");

                    b.ToTable("pensionerDetailModels");
                });
#pragma warning restore 612, 618
        }
    }
}
